# Geometry Analysis Homework solution

In [3]:
import numpy
import os
#import os reads in file

In [4]:
#opening, reading, and storing in a variable
#os.path.join reads in the actual file
file_location = os.path.join('data', 'water.xyz')
print(file_location)

data/water.xyz


In [6]:
xyz_file = numpy.genfromtxt(fname=file_location, dtype='unicode', skip_header=2)
#skip_header skips the two lines with three columns

In [7]:
print(xyz_file)

[['O' '0.000000' '-0.007156' '0.965491']
 ['H1' '-0.000000' '0.001486' '-0.003471']
 ['H2' '0.000000' '0.931026' '1.207929']]


In [8]:
symbols = xyz_file[:,0] #every row, just column 1
coordinates = xyz_file[:,1:] #every row, column 2 to the end
print(symbols)
print (coordinates)
#two slices to separate off symbols and coordinates

['O' 'H1' 'H2']
[['0.000000' '-0.007156' '0.965491']
 ['-0.000000' '0.001486' '-0.003471']
 ['0.000000' '0.931026' '1.207929']]


In [9]:
coordinates = coordinates.astype(numpy.float)
#astype(numpy.float) casts all coordinates at once, much faster
#gets rid of strings and saves as numbers instead

In [10]:
print(coordinates)

[[ 0.       -0.007156  0.965491]
 [-0.        0.001486 -0.003471]
 [ 0.        0.931026  1.207929]]


$$ distance = \sqrt{(x1-x2)^2 + (y1-y2)^2 + (z1-z2)^2} $$

In [16]:
num_atoms = len(symbols)
for num1 in range(0,num_atoms):
    for num2 in range(0,num_atoms):
        #print(F'Atom 1 is {num1}')
        #print(F'Atom 2 is {num2}')
        if num1<num2:
            x_distance = coordinates [num1,0]-coordinates[num2,0]
            y_distance = coordinates [num1,1]-coordinates[num2,1]
            z_distance = coordinates [num1,2]-coordinates[num2,2]
            distance_12  = numpy.sqrt(x_distance**2+y_distance**2+z_distance**2)
            if distance_12 > 0 and distance_12 <= 1.5:
                print(F'{symbols[num1]} to {symbols[num2]} : {distance_12:.3f}')
            

O to H1 : 0.969
O to H2 : 0.969


In [18]:
import numpy
import os

file_location = os.path.join('data', 'water.xyz')
xyz_file = numpy.genfromtxt(fname=file_location, dtype='unicode', skip_header=2)
symbols = xyz_file[:,0] 
coordinates = xyz_file[:,1:] 
coordinates = coordinates.astype(numpy.float)
num_atoms = len(symbols)
for num1 in range(0,num_atoms):
    for num2 in range(0,num_atoms):
        if num1<num2:
            x_distance = coordinates [num1,0]-coordinates[num2,0]
            y_distance = coordinates [num1,1]-coordinates[num2,1]
            z_distance = coordinates [num1,2]-coordinates[num2,2]
            distance_12  = numpy.sqrt(x_distance**2+y_distance**2+z_distance**2)
            if distance_12 > 0 and distance_12 <= 1.5:
                print(F'{symbols[num1]} to {symbols[num2]} : {distance_12:.3f}')
            

O to H1 : 0.969
O to H2 : 0.969
